### ISSUE TITLE
worker dies after a few minutes

### ISSUE THREAD

**Issue by unclevito2017** [brichard19/parcrypt#1]
![parcrypt](https://user-images.githubusercontent.com/37158637/155259437-d670066c-e90a-4d56-8c51-44ddd7f144d6.jpg)

**Comment by JasY95** [comment]
I was unable to compile the client on windows.

**Comment by unclevito2017** [comment]
here is the parcrypt.exe I compiled https://github.com/unclevito2017/parcrypt

**Comment by brichard19** [comment]
Hi,

The error detection and handling has been improved. Please give it another try and let me know if any errors are reported.

Thanks

**Comment by unclevito2017** [comment]
Seems to work well now. Found a typo in your readme that causes an error when testing, Readme has:
python server/make_project.py --name test_project --challange 44
should be python server/make_project.py --name test_project --challenge 44
or in windows python make_project.py --name test_project --challenge 44
